version: 2
jobs:
  build:
    working_directory: /go/src/github.com/micnncim/reviewdog-test
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run reviewdog
          command: |
            go get github.com/haya14busa/reviewdog/cmd/reviewdog
            go get golang.org/x/lint/golint
            make reviewdog
