version: 2
jobs:
  build:
    working_directory: /go/src/github.com/micnncim/reviewdog-playground
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run reviewdog
          command: |
            go get github.com/reviewdog/reviewdog/cmd/reviewdog
            go get golang.org/x/lint/golint
            go get github.com/dominikh/go-tools/cmd/unused
            go get github.com/dominikh/go-tools/cmd/gosimple
            go get github.com/dominikh/go-tools/cmd/staticcheck
            go get github.com/kisielk/errcheck
            go get github.com/client9/misspell/cmd/misspell
            go get mvdan.cc/unparam
            go get github.com/mgechev/revive
            go get github.com/golangci/golangci-lint/cmd/golangci-lint
            reviewdog -reporter='github-pr-review'
