version: 2
jobs:
  build:
    working_directory: /go/src/github.com/micnncim/reviewdog-test
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run reviewdog
          command: |
            go get -u github.com/haya14busa/reviewdog/cmd/reviewdog
            go get -u golang.org/x/lint/golint
            reviewdog -reporter='github-pr-review'
